services:

  user-postgres:
    image: postgres:15
    container_name: meetcall_users_db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    networks:
      - internal

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: meetcall_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: meetcall_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal

  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    networks:
      - internal

volumes:
  user_pgdata:
  keycloak_pgdata:

networks:
  internal:
    driver: bridge
