services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: meetcall_keycloak
    command: start-dev #start for production
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8081:8081"
    depends_on:
      - keycloak-postgres
    networks:
      - internal

  keycloak-postgres:
    image: postgres:15
    container_name: meetcall_keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  keycloak_pgdata:

networks:
  internal:
    driver: bridge
