spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_URI:https://github.com/Funt1koff/meet-call-config}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-service:8761/eureka}
