spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/meetcall-realm

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
